### ISSUE TITLE
Flash is Dead!!

### ISSUE THREAD

**Issue by l8nite** [pakastin/open-source-flash#1]
https://www.youtube.com/watch?v=L0nuQ5o2DYU

**Comment by pakastin** [comment]
Flash is dead yes, but for archive reasons there should be a way to browse old projects.
I started my web career with Flash 4 in 1999 and I have a lot of cool projects done with it.

After 2020 who knows if it's possible to view them anymore?

**Comment by BartoszCki** [comment]
Well instead of trying to raise the dead you could for instance download the installer now while it's still available ;)

**Comment by SG5** [comment]
@pakastin use virtualbox with windows xp, install flash for IE 7 and you will be able to solve flash problem in 2020

**Comment by pakastin** [comment]
And __that's__ safe? 😂

**Comment by sevans-ge** [comment]
Maybe not XP/IE 7, but that's the approach you'll need to take in order to work in a browser that will actually still support installing/running Flash.

**Comment by ancarda** [comment]
A virtual machine is a safe way to carry on - the alternative is you run Flash, software that's known to have security vulnerabilities over running it in a VM where you can have no personal or important data on it and can reset it if you (somehow) get a virus.

FIrefox's roadmap is ripping out support for plugins in the next few years so you'll eventually have to run an older version of your browser eventually or a Flash-enabled fork that may not be as well maintained - both put you at even greater risk.

I appreciate we should keep historical content alive, but a virtual machine is the right approach here. Modern systems need to move on and dropping Flash and NPAPI is inevitable.

**Comment by pakastin** [comment]
I'm not saying it should stay as a browser plugin, but opening the spec would open possibilities we can't even imagine.

**Comment by daveloyall** [comment]
Keep in mind folks, this isn't a petition to save flash, it's a petition to get Adobe to release the source code for flash.  Once that source is released, if some hackers in 2025 want to create a virtual reality of gallery of old flash games, more power to them!

**Comment by pakastin** [comment]
@daveloyall My thoughts exactly! 😎👍

**Comment by Zegnat** [comment]
> I’m not saying it should stay as a browser plugin, but opening the spec would open possibilities we can’t even imagine.

… but isn’t this already the case? Adobe has [a page all about the SWF format](https://www.adobe.com/devnet/swf.html), with [a published PDF of the SWF File Format Specification](https://wwwimages2.adobe.com/content/dam/Adobe/en/devnet/swf/pdf/swf-file-format-spec.pdf). That is version 19, but they even keep older specifications around for posterity. Like [the specification for version 10](http://wwwimages.adobe.com/www.adobe.com/content/dam/Adobe/en/devnet/swf/pdf/swf-file-format-spec-v10.pdf).

The Archive Team’s [File Format wiki](http://fileformats.archiveteam.org/) has been [keeping track of SWF](http://fileformats.archiveteam.org/wiki/SWF) as well. This is literally what people do “for archive reasons”.

> <i>[…]</i> it’s a petition to get Adobe to release the source code for flash.

If it is open-source you are after, the File Format wiki [points you](http://fileformats.archiveteam.org/wiki/SWF#Software) in the right direction as well:

* [Gnash](https://www.gnu.org/software/gnash/) — “the GNU Flash movie player”
* [Lightspark](https://lightspark.github.io/) — “A free, open source Flash player”
* [Shumway](https://github.com/mozilla/shumway) — “a faithful and efficient renderer for the SWF file format”

You know what the problem with those is? Most of them have grown stagnant. You want to ensure free and future access to Flash? Go and help those projects out! Go and implement the spec Adobe has been kind enough to publish, go and pay programmers for their time. Those are the same things that would need to happen if Adobe does share their code anyway, why not start today!

And if you are not a programmer? Well, you could start archiving. Help the File Format wiki out by collecting resources about the SWF format, and put those resources on the Internet Archive. Start pushing old SWF games and content to the Internet Archive so when 2020 comes along you still have something to look at instead of finding out Newgrounds is down because nobody pays (I hope [**you** are](https://www.newgrounds.com/supporter)) for that same Flash content.

I love my archives. I am all for personal archiving. I am saddened to see a technology disappear. But I feel a petition does not solve those issues.

And now I will close off with a link to my favourite Flash game of all time. [Pearls Before Swine.](http://www.transience.com.au/pearl.html)

**Comment by pakastin** [comment]
Thank you for sharing these! Is `.fla` still closed format?

**Comment by Zegnat** [comment]
> Is `.fla` still closed format?

This will depend on your definition of closed. I don’t remember any specification being available, but you can argue specifications are unnecessary because the file isn’t an irreversibly compiled binary blob in the first place.

As far as I know [this StackOveflow answer](https://stackoverflow.com/a/28262081) is still accurate (Wikipedia [agrees with it](https://en.wikipedia.org/wiki/SWF#Related_file_formats_and_extensions) too):

> CS4 FLA container is [Microsoft Structured Storage](http://en.wikipedia.org/wiki/Compound_File_Binary_Format) (like MS Word documents). You can open it with for example FAR Manager or OpenMCDF. Embedded AS3 code can be seen inside the objects in Unicode plaintext. You can open it with a text editor that supports Unicode encoding (2-byte UCS-2 Little Endian, not UTF8), and trim off binary garbage.
>
> CS5 FLA is just a ZIP with AS3 code inside DOMDocument.xml.

So while lacking a specification anyone should be able to open up an FLA-file and extract the ActionScript, images, and all other resources that were used.

I am not sure if there are SWF compilers available outside of Adobe Flash to turn the resources into an SWF file again… I seem to recall something about [old Haxe](http://old.haxe.org/) being able to compile AS, but don’t take my word for it.

At that point we are talking about reconstructing the development environment and that is out-of-scope for most archiving projects. If (for some arcane reason) you need to be able to keep compiling AS1 code into SWF version 6 files you should just consider emulating that environment in its entirely and go with the VMs as mentioned by @ancarda.

**Comment by pakastin** [comment]
Thanks for the info!

**Comment by demurgos** [comment]
> I am not sure if there are SWF compilers available outside of Adobe Flash to turn the resources into an SWF file again… I seem to recall something about old Haxe being able to compile AS, but don’t take my word for it.

You can still use [Haxe](http://haxe.org/documentation/introduction/compiler-targets.html) to compile to Flash. It targets AS3, and using it with [the OpenFl](http://www.openfl.org/) library you can keep the Flash API, load assets, and so on. If you need to target AS2, the last version supporting it is Haxe 3.1 (flash8 target). The official 3.1 version is no longer compatible with the latest `zlib` version so I patched it and maintain [a working 3.1 branch](https://github.com/demurgos/haxe/tree/3.1_bugfix), there's [an open issue](https://github.com/HaxeFoundation/haxe/issues/5977) to move it to the main repo.

**Comment by Zegnat** [comment]
@demurgos thanks for confirming!

So we have open-source SWF compilation as well as open-source SWF players out there right now. Not sure what Adobe would add by disclosing their source other than another unmaintained SWF player.

**Comment by GeorgeWL** [comment]
Guess just it lets' there be it visible purely for posterity?
@Zegnat

**Comment by gporos** [comment]
There are useful sites which still use flash.  For example the National Weather Service Enhanced Radar Image Loop.    
https://radar.weather.gov/radar.php?rid=grr&product=N0R&overlay=11101111&loop=yes
Even though flash is being "depreciated", it seems the government does not want to waste taxpayers dollars to convert a perfectly functional page.

**Comment by GeorgeWL** [comment]
@gporos there are automated services that are free and can convert flash assets.

There's no excuse.

**Comment by jduncanator** [comment]
Not to mention that the Flash byte code (ABC) and the Flash VM specifications (AVM2) have already been released (albeit in 2007) [here](http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/actionscript/articles/avm2overview.pdf). With this information one could build their own Flash player as it provides all the information required to parse both SWF files (see previous comments for the SWF  format documents) as well as the format of the byte code embedded in these files.

Sure, Adobe could release a more up to date version of this document, but I doubt much will have changed over the years as these are pretty basic op codes with very little room for improvement.

**Comment by Zegnat** [comment]
> That’s all fine and dandy for now, however, come 2020 when browsers remove Flash from their releases (no browser is going to include a piece of software that has been discontinued by its manufacturer), those pages will become fairly “non-functional”.

And don’t forget they have discontinued platform support before. Android hasn’t had support since 4.1 (Jelly Bean) in 2012, Flash was [pulled from the Play Store](https://arstechnica.com/information-technology/2012/08/availability-of-adobes-flash-browser-plugin-discontinued-on-android/) back then.

What with Android and iOS making up the majority of the tablet market, and tablets becoming prevalent even over laptops amongst certain age groups, it is horribly irresponsible for any government website to insist on using technology that actively bars people from making use of their public services.

@gporos you say “the government does not want to waste taxpayers dollars to convert a perfectly functional page”, I say the government is refusing to invest taxpayers’ dollars into making public services accessible to those same taxpayers.
