### ISSUE TITLE
What is the source for “closed source of Flash spec” being a problem for current open-source SWF players?

### ISSUE THREAD

**Issue by Zegnat** [pakastin/open-source-flash#22]
https://github.com/pakastin/open-source-flash/commit/46b9d58a88871d9b4cba4da1ae76a3a2b90aee31 adds links to current open-source projects (yeey 🎉) but also says the reason they are incomplete is because of Flash being closed source. This was then rewritten to “Flash spec” in https://github.com/pakastin/open-source-flash/commit/66ed6c63398deb2fea7bcf54212b3fbba4a7fa3d.

1. What makes the specification “closed source”? The specification is available. Or are there parts missing from the public specification?
   
2. Why are those projects incompletion linked to the closed source status of Flash? Are there any sources for e.g. issues on those projects that are blocked by Adobe Flash?

**Comment by madovsky** [comment]
I think it's better to not care of closed source anymore since they plan to stop it.
So there is no legitimate license laws (at least international, but maybe US only) that force a politically 
wanted death of a (still better than other) technology and continue to protect a dead entities of the code use, especially when millions websites depend on it, which is I think a massive law issue.

**Comment by pakastin** [comment]
Duplicate to #54, closing
