### ISSUE TITLE
Shockwave should be released too if flash is

### ISSUE THREAD

**Issue by asdfjk1** [pakastin/open-source-flash#28]
Shockwave was used heavily in the 90s and up till the mid 00s for games and any interactive content especially on the web. It was used alongside flash for many years and was mentioned in the blog update killing flash. If flash gets open sourced then shockwave should be open source as well.

**Comment by pakastin** [comment]
True!

**Comment by lesmana** [comment]
here is one shockwave content i remember to go around the internet:
http://www.platinumgrit.com/pokethebunny.htm
since moving to linux i was not able to play it anymore since adobe never released shockwave for linux. at least not that i know of.
here is a video of poke the bunny in action:
https://www.youtube.com/watch?v=MiVEvAQOV4U

**Comment by pakastin** [comment]
Added to README, so closing..
