### ISSUE TITLE
For people who don't understand why we need flash open sourced

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [pakastin/open-source-flash#67]
Many developers and projects developed amazing flash applications for companies, or for their own interest during the last 20 years. Until today they are still running, using better system/cpu resources than any kind of javascript since flash player (version 26 today) learned and fixed a lot of issues during this time.

Some projects developers and I asked months and even years to get a very stable version, which includes sometimes millions line of code. As you can see, for various valid and logical reason, these projects won't be developed again and again for the only reason that the development "zeitgeist" is changing every 10 years.
It's totally absurd and even dangerous for the freedom of Internet.

I recall to develop a Perl application 18 years ago to automate invoices of a payment system for a company, during this time I had to change a very few function names and logic, but today it's still working flawlessly.
The web SHOULD be like that, don't waste developers to reprogram everything decade after decade, it does not make sense at all, especially when the major tech used is not better and even worse than the previous.
To go forward and avoid to reinvent the wheel again and again, The role of a web browser is to be compatible with an absolute anachronism, thus to prevent any bad guys to control the web technology.

I hope people, trolls and other who definitely not understood why we need flash as open source will now get a better clue of why we absolutely need it done. We have 3 years before the end of the game.

Good luck everybody

**Comment by pakastin** [comment]
If you have any ideas for README, please feel free to create a pull request 😉

**Comment by madovsky** [comment]
Ok, so I delete this issue?

**Comment by madovsky** [comment]
Ok done, thanks to delete this issue.

**Comment by pakastin** [comment]
Let's keep it open for a while to have a conversation 😎

**Comment by FSMaxB** [comment]
@madovsky: The world is changing, and software has to be improved upon and rewritten if it is unsafe. I think it only makes sense to have flash in a standalone fashion, like Java Applets (which were really popular back in the day). That way you still get access to historic software, especially art and games, where there is no monetary incentive to ever rewrite it.

But still allowing to embed flash in web pages is just a bad idea, because the attack surface is just too big. Web Browsers are bad enough as it is. If your website completely relies on flash, and there is no way for it to be rewritten, the only possible solution would be some kind of emulation/transpilation to WebAssembly or similar.

Let me give you an example of what I mean: Back in the day, many companies were relying on software written for MS-DOS. But today nobody is crying over Microsoft not having full DOS support. New technology took over and if you have something that you couldn't port, you would have to rely on projects like dosbox or FreeDOS for your programs to run. But nobody seriously demands from Microsoft that they natively support DOS software on Windows 10.

Windows XP is another example: If you want to use XP software that doesn't run on newer versions of Windows or on Mac or Linux via Wine, then you would have to confine a Windows XP machine into an environment that cannot communicate with the outside, because there is no support anymore (if you cannot spare a few million dollars every now and then), but you wouldn't expose that machine to the internet (which would be the equivalent of still having flash in the browser).

**Comment by FSMaxB** [comment]
All I'm saying is: Yes, we need it open sourced, so that old software can still be used, but please keep it away from the Web!

**Comment by madovsky** [comment]
what you think is old is not anymore bad.... it's a control minded myth

**Comment by My1** [comment]
Well old doesn't have to be bad but flash is a security desaster, and before flash gets open source AND an audit that everything is okay, it should not be used for web stuff imo.

**Comment by madovsky** [comment]
please stop to continue to repeat what you don't even know.... it's very boring

**Comment by FSMaxB** [comment]
Taking a look at the list of horrible vulnerabilities that flash has much much too often, the source code has to be terribly bad. So bad that Adobe wasn't able to fix it in years. That makes me think that the only way to fix it is to completely reimplement it.

And if you do that, you could just improve what's already there, and try to "emulate" flash on that.

**Comment by FSMaxB** [comment]
That's not saying anything about how good or bad flash is as a development framework. Just about the implementation.

**Comment by madovsky** [comment]
Pakastin: please block this thread, enough is enough

**Comment by FSMaxB** [comment]
Just face it. C and C++ are horribly unsafe languages and using them is like walking through a mine field. Just that the mines might blow up with a delay of several years or decades.

Back in the day there was less focus on security when developing in these languages. I don't blame Adobe here. They did what was the standard back then, and after that probably did their best to clean it up. But it's just too hard. 

I hate C and C++ because I use it every day, not because I'm blindly following other people's opinions.

But I have said everything that I had to say. No need to block anything.

🤐 (except somebody wants another statement from me)

**Comment by madovsky** [comment]
Pakastin: I think this thread is not to let people what they think or not of flash, we f..... don't care,
our goal is to save millions of project that cannot be reprogrammed for various reason. so I think
we absolutely must moderate intelligently this git or quickly a lot of fascists will pollute it

**Comment by My1** [comment]
well yeah for old projects, but @FSMaxB said:
> Yes, we need it open sourced, so that old software can still be used, but please keep it away from the Web!


fine for older and internal things but as long as flash is unsafe as hell people shouldnt think of making newer things for the web in flash

**Comment by madovsky** [comment]
guys, you just repeating endlessly what steve jobs said 10 years ago..... STOP!

**Comment by demurgos** [comment]
I spent the last few years maintaining Flash projects, the technology is/was good but the environment is/was the issue.

In my opinion, the real issue never was that **Flash is old**: modern does not always mean better (even if it means that you can use previous experiences to iterate). The problem, and it is addressed by this repo, is that you invested millions of lines of code in a platform that you fundamentally don't control. Now, you may have concerns against Javascript et al, but you have to admit that the risk of such event happening to the Web technologies are fairly lower.
It is also hard to deny that the lack of audit and widespread use of Flash made it the target of many attacks and it was the source of a lot of pain. I am working on preserving existing content (mainly for archival purposes), but accumulating more debt by persisting with Flash is unwise in my opinion.

**Comment by My1** [comment]
when did steve say that flash is okay to use when it gets revemed for security (also I am not an apple fan, quite the contrary)

on a more serious note:

I agree with @demurgos totally. flash is not bad because of it's age but its circumstances.

**Comment by madovsky** [comment]
god, sterile thread another time.... it's frustrating...

**Comment by demurgos** [comment]
What do you expect us to say? I acknowledged that large projects were made in Flash and I am actively working on preserving them. It does not exempt me from having a critical look at the state of today's technologies.

> The web SHOULD be like that, don't waste developers to reprogram everything decade after decade

> JS will be soon a disaster for a lot of you, you will see.

I believe that this is the heart of the current disagreement and hope that this message will clarify my position.

To put it simply, my definition of the Web is "the W3C web": a family of open standards implemented by multiple competing actors. This web "IS like that": just as your example with Perl, I have some 10 year old website that I can open and they all run flawlessly, and it will continue to work flawlessly. I participate with some of the current discussions around Node, and I am fairly confident that my programs will still work in 20 years. Flash was never part of this web.

The difference between Perl and Flash is that the nature of Flash (being held by a single corporation) never guaranteed the long term stability of the platform. As an example, Node was initially controlled by a single company (Joyent) but since it got an independent technical committee it is much healthier. Last week's announcement helped many to realize their dependency on the whims of Adobe. Truly, I don't think that @My1 and @FSMaxB are trolling. They both understand (I guess) that the situation is causing trouble to many organizations and they are just trying to express what the current is (not what you wish it would be) with the deprecation of Flash.

**My problem is that you never controlled Flash, not that it had vulnerabilities or that Jobs wanted to get rid of competition for the apps of his phones.**

**Comment by MartinItsLinda** [comment]
No need to throw your dummy out the pram here, perhaps you should listen to what some people have to say. They're not saying that flash is bad because it's old, they're saying it's bad because of the amount of security flaws it has. It has been the cause of thousands of security breaches and will continue to be if people use it. A company that has billions of dollars a d thousands of programmers couldn't fix the issues there were with flash, so what makes you think you can? It's just better to find alternatives at this point or try and reimplement it in a way that looks and feels like flash but that is better maintained than flash and more secure than flash.

**Comment by madovsky** [comment]
ok, trolls are on a big number here. you can say whatever you want guys, this git is not to let you continue to spread insanity about this tech or this tech.
unbelievable how people are so ignorant or naive about this subject
demurgos: 
who do you think control the web standard today? people like you and me? (laught)
do you know how is behind W3C?, search club of 33, to open a door to the real reality.

**Comment by pakastin** [comment]
Here's the whole list of W3C members: https://www.w3.org/Consortium/Member/List

**Comment by My1** [comment]
well true control is a problem with anything but at least it's not just one company but a larger set of actors, also the standard itself is pretty open and anyone can build stuff for it, while with flash you just have the one thing from adobe and that's it.


but flash iirc is a pretty proprietary thing and to top it, one flaw is coming after the next one.

**Comment by madovsky** [comment]
My1: that's why we are working on to find a solution by opening a git repository, period.

**Comment by My1** [comment]
yeah and I did say that flash is generally okay, as soon as it's open and tested secure quite a few posts ago, but in the state it is and probably will also stay for months or years, flash is not good for the web and shouldnt be used productively.

**Comment by madovsky** [comment]
My1: we don't care of your opinion on flash, this git is done to express what you think on flash.
this git is done to find a solution of how to keep alive millions of projects.

**Comment by demurgos** [comment]
@madovsky
Please refrain from personal attacks ("trolls are on a big number here.", "we don't care of your opinion"). We may express views that you disagree with regarding the comparison between Adobe and the W3C but insulting members of this conversation won't help us find a solution.

> this git is done to find a solution of how to keep alive millions of projects

I agree with this. That's why I consider that identifying the use cases for such an endeavor is important to frame the scope of an open source initiative and get a hold of the priorities.
There are other very interesting issues discussing the technical aspects of the preservation of Flash.
Having one discussion about the motivations behind this git is also valuable and wouldn't hurt.

We all agree that Flash is important and we need a way to keep it working. I feel that for the main part, people mean "for archival purposes" but you want to maintain Flash at the current state (or better). This kind of support is more complex and requires an active community (so the discussion is relevant). Better understanding the needs of maintainers of very large Flash code bases would help. You refer to other developers working on projects with millions of lines of code. Could you share you experience more specifically? Tell us more about these projects?

**Comment by pakastin** [comment]
Yeah, lets keep the [Code of Conduct](https://github.com/pakastin/open-source-flash/blob/master/CODE_OF_CONDUCT.md) in mind

**Comment by madovsky** [comment]
demurgos:
"You refer to other developers working on projects with millions of lines of code. Could you share you experience more specifically? Tell us more about these projects?"
again this git repository is not to proof anything on if flash is good or not, or if flash is still a good tech.
obviously you cannot delete 20 years of web contents, and frankly I have no interest to show you anything on this subject, becaus it's NOT the subject.
we need technical people here to hack flash code and do better than all the javascript crap, we need as much as alternative we can, preserving the memory of the web, the rest is just unuseful blablah

**Comment by madovsky** [comment]
pakastin: sure that the code of conduct is important here,
freedom of speech is a must as long as no insult against a specific person is made.

**Comment by pakastin** [comment]
Sure!

**Comment by My1** [comment]
Well calling someone a troll even of implicitly or saying their opinion doesn't matter sure isn't nice.

**Comment by MartinItsLinda** [comment]
@madovsky It kind of is relevant, you're saying flash should still be used, we're asking you why it should and what makes it better than JS and you're just saying that you don't need to prove it.

**Comment by madovsky** [comment]
MartinItsLinda: ...

**Comment by demurgos** [comment]
> demurgos:
"You refer to other developers working on projects with millions of lines of code. Could you share you experience more specifically? Tell us more about these projects?"
Do you really think that nothing big was developed in actionscript during the last 20 years?
again this git repository is not to proof anything on if flash is good or not,
obviously you cannot delete 20 years of web contents, and frankly I have no interest to show you anything on this subject, because it's NOT the subject.
we need technical people here to hack flash code and do better than all the javascript crap, we need as much as alternative we can, preserving the memory of the web, the rest is just unuseful blablah propaganda

@madovsky 
I wanted to refocus the discussion on content. I was referring to this sentence in your first message:
> Some projects developers and I asked months and even years to get a very stable version, which includes sometimes millions line of code.

Do you have personal experience with million-line projects involving Flash? If so, I am very eager to learn more a bout it. Is it for games? Video? Advertisement? Is it used through the player? Redtamarin? Embedded? What kind of sectors used these programs?
